<div class="col-lg-<?php echo $span;?> col-md-<?php echo $span;?> col-sm-<?php echo ($cols > 2 && $cols % 2 == 0) ? $span * 2 : $span; ?> col-xs-<?php echo $mini;?> _item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> product-col <?php if($layout_mode !='grid'){ echo "col-fullwidth";} ?> ">
<div class="wrap-item">
    <div class="product-block">
            <?php
            $module = rand().time();
            if(isset($enable_deals) && $enable_deals){
                    // Get the Discount
                    $save_price = (float)$_product->getPrice() - (float)$_product->getSpecialPrice();
                    $save_price_currency = Mage::helper('core')->currency($save_price, true, false);
                    $discount = round(($save_price/$_product->getPrice())*100);
                    $discount_string = " ".$discount."% Off";
            }
            ?>
            <?php
                $swap_class = "";
                $productId = $_product->getId();
                if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) {
                        $swap_class = "swap";
                 } 
            ?>

            <?php  //Sale Icon ?>
            <?php 
            if($enable_sale_icon) {
                // Get the Special Price

                $specialprice = $_product->getSpecialPrice(); 
                // Get the Special Price FROM date
                $specialPriceFromDate = $_product->getSpecialFromDate();
                // Get the Special Price TO date
                $specialPriceToDate = $_product->getSpecialToDate();
                // Get Current date
                $today =  time();
             
                if ($specialprice) {
                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
            ?>
                    <span class="onsale"><span><?php echo $this->__("Save")."<br>".$discount_string;?></span></span>
            <?php  
                    }
                }
            }
            ?>
                    <div class="image <?php echo $swap_class; ?>">
                        
                            <?php // New icon ?>
                             <?php
                                if($enable_new_icon) {
                                    $is_new = Mage::helper("ves_tempcp")->checkProductIsNew( $_product );
                                    
                                    if($is_new) { ?>
                                    <span class="new-icon"><span><?php echo $this->__("New");?></span></span>
                                    <?php

                                    }
                                }
                            ?>
                           <div class="product-img img">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image img">
                            <img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            <?php if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) { ?>
                                    <span class="hover-image">
                                        <a class="img" href="<?php echo $_product->getProductUrl(); ?>"><img class="img-responsive" src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
                                    </span>
                            <?php } ?>

                            <div class="right"> 

                            <ul class="add-to-links">
                                <?php if($show_compare_wishlist): ?>
                                    <li class="link-wishlist">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <a data-placement="top" data-toggle="tooltip" data-original-title="<?php echo $this->__('Wishlist') ?>" class="wishlist fa fa-heart-o" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" ></a>
                                        <?php endif; ?>
                                    </li>

                                    <li class="link-compare">
                                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                            <a data-placement="top" data-toggle="tooltip" data-original-title="<?php echo $this->__('Compare') ?>" class="compare fa fa-refresh" href="<?php echo $_compareUrl ?>"></a>
                                        <?php endif; ?>
                                    </li>
                                <?php endif; ?>

                                <?php if ($quickview) { ?>
                                    <li class="link-quickview">
                                        <a data-placement="top" data-toggle="tooltip" data-original-title="<?php echo $this->__('Quick-View') ?>" class="a-quickview ves-colorbox" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getId() ); ?>"><span class="fa fa-eye"></span></a>
                                    </li>
                                <?php } ?>

                                 <?php // Image Popup ?>
                                <?php if( $enable_pzoom ): ?>
                                    <li class="link-zoom">
                                        <a data-placement="top" data-toggle="tooltip" data-original-title="<?php echo $this->__('Zoom') ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($popup_image_width, $popup_image_height);?>" class="colorbox product-zoom" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"><span class="fa fa-search-plus"></span></a>
                                    </li>
                                <?php endif; ?>
                            </ul>
                          
                            </div>
                            
                        </div>
                    </div>

                   

                    <?php if($layout_mode !='grid'): ?>
                    <?php endif; ?>
                    <?php // Product description ?>

                    <div class="product-meta product-shop">
                        <div class="left">                           
                            
                            <?php if( $show_title ): ?>
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h3 class="product-name name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h3>
                            <?php endif; ?>
                            
                            <?php if($show_review) { ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, true, true)?>
                            <?php } ?>

                            <?php if($enable_short_desc): ?>
                                <div class="desc std" itemprop="desc">
                                    <?php
                                        $product_short_desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
                                        echo Mage::helper("ves_tempcp")->subString($product_short_desc, $desc_maxchar, "");
                                    ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            <?php endif; ?>

                            <div class="price-deal">
                            <?php if($show_price): ?>
                                <div class="price">
                                    <?php echo $this->getPriceHtml($_product, true, $price_prefix) ?>
                                </div>
                            <?php endif; ?>


                             <?php if(isset($enable_deals) && $enable_deals){ ?>
                                <div class="deal_detail">
                                        <ul>
                                            <li>
                                                <span><?php echo $this->__("Discount");?></span>
                                                <span class="deal_detail_num"><?php echo $discount;?>%</span>
                                            </li>
                                            <li>
                                                <span><?php echo $this->__("You save");?></span>
                                                <span class="deal_detail_num"><span class="price"><?php echo $save_price_currency; ?></span></span>
                                            </li>
                                            <li>
                                                <span><?php echo $this->__("Bought");?></span>
                                                <span class="deal_detail_num"><?php echo Mage::helper("ves_tempcp")->getBought($_product->getSku());?></span>
                                            </li>
                                        </ul>
                                </div>
                            <?php } ?>

                            <?php if(isset($enable_deals) && $enable_deals){ ?>
                            <?php 
                                $date1 = date('G:i:s', strtotime($_product->getSpecialToDate()));
                                if ($date1 == "0:00:00") {
                                    $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($_product->getSpecialToDate()));
                                }else{
                                    $targetDate = date('m/d/Y G:i:s', strtotime($_product->getSpecialToDate()));
                                } 
                            ?>
                            <div class="productdeals">
                                <div class="item-detail">
                                        <div class="timer-explain">(<?php echo date('m/d/Y', strtotime($_product->getSpecialToDate())); ?>)</div>   
                                </div>
                                <div id="item<?php echo $module; ?>countdown_<?php echo $_product->getId(); ?>" class="item-countdown"></div>
                                <script type="text/javascript">
                                jQuery(document).ready(function($){
                                        $("#item<?php echo $module; ?>countdown_<?php echo $_product->getId(); ?>").lofCountDown({
                                            formatStyle:2,
                                            TargetDate:"<?php echo $targetDate; ?>",
                                            DisplayFormat:"<ul><li>%%D%% <div><?php echo $this->__('Days');?></div></li><li> %%H%% <div><?php echo $this->__('Hours');?></div></li><li> %%M%% <div><?php echo $this->__('Mins');?></div></li><li> %%S%% <div><?php echo $this->__('Secs');?></div></li></ul>",
                                            FinishMessage:"<?php echo $this->__('Expired');?>",
                                        });
                                    });
                                </script>
                            </div>
                            <?php }?>
                            </div>
        
                            <div class="action">
                            <?php if($show_addcart): ?>
                                <div class="cart">
                                    <?php if($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-shopping-cart btn-outline" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                </div>
                            <?php endif; ?>                          
                            </div>
                        </div>
                            
                    </div>

        
            </div>
        </div>

</div>

    
