<?php 

$route = Mage::app()->getRequest()->getRouteName(); 

$media_cols = array("md" => 6,
                    "sm" => 12,
                    "xs" => 12);

$product_cols = array("md" => 6,
                    "sm" => 12,
                    "xs" => 12);
/*If quickview popup are openning don't change column number of media block and product information block*/
if($route == "tempcp") {
    $media_cols = array("md" => 5,
                    "sm" => 5,
                    "xs" => 5);

    $product_cols = array("md" => 7,
                    "sm" => 7,
                    "xs" => 7);
}
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <div class="product-view detail-style2 product-info" itemscope itemtype="http://data-vocabulary.org/Product">
        <meta itemprop="url" content="<?php echo $_product->getProductUrl() ?>"/>
        <div class="product-essential row">
                <div class="col-lg-5 col-md-<?php echo $media_cols['md'];?> col-sm-<?php echo $media_cols['sm'];?> col-xs-<?php echo $media_cols['xs'];?> image-container product-img-box">
                    <?php echo $this->getChildHtml('media') ?>
                </div>

                <div class="col-lg-7 col-md-<?php echo $product_cols['md'];?> col-sm-<?php echo $product_cols['sm'];?> col-xs-<?php echo $product_cols['xs'];?> product-shop product-view">
                    <div class="border space-padding-30">
                        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            
            
                            <?php echo $this->getBlockHtml('formkey') ?>
                            <div class="no-display">
                                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                                <input type="hidden" name="related_product" id="related-products-field" value="" />
                            </div>
                
                            <h1 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                           
                            <div class="review" itemprop="review" itemscope itemtype="http://data-vocabulary.org/Review-aggregate"> <?php echo $this->getReviewsSummaryHtml($_product, 'aggregate', true)?> </div>

                            <div itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer" class="price">
                                <?php echo $this->getChildHtml('product_type_data') ?>

                                <?php echo $this->getTierPriceHtml() ?>  
                            </div>
                            
                            <?php echo $this->getChildHtml('alert_urls') ?>

                            <?php  if($themeConfig->get("enable_sku", 0)){  ?>
                                <p><?php echo $this->__('Product Code: ').$_product->getSku(); ?></p>
                            <?php } ?>

                            <?php echo $this->getChildHtml('extrahint') ?>
                                
                            <div class="description"> 
                                 <?php if ($_product->getShortDescription()):?>
                                <div class="short-description">
                                    <div class="std" itemprop="description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                                </div>
                                <?php endif;?>
                            </div>

                            
                            <div class="product-extra">   
                                <?php if (!$this->hasOptions()):?>
                                    <div class="add-to-box">
                                        <?php if($_product->isSaleable()): ?>
                                            <?php echo $this->getChildHtml('addtocart') ?>                                
                                        <?php endif; ?>
                                        <?php echo $this->getChildHtml('addto') ?>
                                    </div>

                                    <?php echo $this->getChildHtml('extra_buttons') ?>

                                    <?php elseif (!$_product->isSaleable()): ?>

                                    <div class="add-to-box">
                                        <?php echo $this->getChildHtml('addto') ?>
                                    </div>
                                <?php endif; ?>
                            </div>

                                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                                <div itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer">
                                    
                                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                                   
                                </div>
                                <?php endif;?>

                            <div class="cat-tag">
                                <div class="cat-product">
                                <span><?php echo $this->__('Category: ') ?></span>
                                <?php $categoryIds = $_product->getCategoryIds();
                                $a = 0;
                                foreach($categoryIds as $categoryId) {
                                    $_cat = Mage::getModel('catalog/category')->load($categoryId) ;
                                    if (($a < 3) AND ($_cat->getLevel() != 1)) {    
                                        echo '<a href="' .$_cat->getUrl() .'"> '.$_cat->getName().'.</a>';
                                    }
                                    if ($a == 4) {
                                        echo "...";
                                    }
                                    $a++;
                                }?>
                                </div>

                                <?php $_tags = new Mage_Tag_Block_Product_List(); ?>
                                <div class="tag-product">
                                <span><?php echo $this->__('Tags: ');?></span>
                                    <?php foreach($_tags->getTags() as $tag):?>                            
                                        <a href="<?php echo $tag->getTaggedProductsUrl()?>"><?php echo $tag->getName()?></a>
                                    <?php endforeach;?>
                                </div>
                            </div>

                            <?php  if($themeConfig->get("enable_social", 0)){  ?>
                            <div class="share">
                               <!-- AddThis Button BEGIN -->
                                    <div class="addthis_toolbox addthis_default_style ">
                                    <a class="addthis_button_facebook_like"></a>
                                    <a class="addthis_button_tweet"></a>
                                    <a class="addthis_button_pinterest_pinit"></a>
                                    <a class="addthis_counter addthis_pill_style"></a>
                                    </div>
                                    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-538d2d303ab3eaa0"></script>
                                <!-- AddThis Button END -->
                                    <div style="clear:both"></div>
                            </div>
                            <?php } ?>
                           
                           <?php echo $this->getChildHtml('other');?>


                            <?php echo $this->getChildHtml('info_tabs') ?>
                        </form>

                        <div class="block-tabs accordion nobackground collapse-right">
                            <div id="product-tabs-accordion" class="panel-group"> 
                                <?php
                                    $route = Mage::app()->getRequest()->getRouteName();
                                    $product_additional_data = "";
                                    $tmp_html = "";
                                    $product_customtab = "";
                                    //Description Tab
                                    if($themeConfig->get("enable_product_descriptiontab", 1)) {
                                        foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html){
                                            $tmp_html .= "<div id=\"tab-{$alias}\" class=\"accordion-body panel-collapse collapse block-{$alias}\"><div class=\"accordion-inner panel-body clearfix\">";
                                            $tmp_html .= $html;
                                            $tmp_html .= "</div></div>";
                                            if ($title = $this->getChildData($alias, 'title')){
                                                echo '<div class="panel panel-default accordion-group clearfix">
                                                            <h4 class="accordion-heading panel-heading">
                                                                <a data-parent="#product-tabs-accordion" data-toggle="collapse" class="accordion-toggle" href="#tab-'.$alias.'">'.$this->escapeHtml($title).'</a>
                                                            </h4>'
                                                            .$tmp_html
                                                    .'</div>';
                                            }else{
                                                $title = $this->__($alias);
                                                echo '<div class="panel panel-default accordion-group clearfix">
                                                            <h4 class="accordion-heading panel-heading">
                                                                <a data-parent="#product-tabs-accordion" data-toggle="collapse" class="accordion-toggle" href="#tab-'.$alias.'">'.$this->escapeHtml(ucfirst($title)).'</a>
                                                            </h4>'
                                                            .$tmp_html
                                                    .'</div>';
                                            }
                                        };
                                    }?>
                                    
                                    <?php //Product Tags Tab ?>
                                    <?php if($themeConfig->get("enable_product_tagstab", 1) && $route != "review" && $route !="tempcp") { ?>
                                         <?php if($product_additional_data = $this->getChildHtml('product_additional_data')): ?>

                                                <?php $product_additional_data = '<div id="tab-tags" class="accordion-body panel-collapse collapse block-tags"><div class="accordion-inner panel-body clearfix">'.$product_additional_data.'</div></div>'; ?>
                                                <div class="panel panel-default accordion-group clearfix">
                                                   <h4 class="accordion-heading panel-heading">
                                                        <a href="#tab-tags" data-parent="#product-tabs-accordion" data-toggle="collapse" class="accordion-toggle"><?php echo Mage::helper('ves_tempcp')->__("Product Tags");?></a>
                                                    </h4>
                                                    <?php echo $product_additional_data;?>
                                                </div>
                                            <?php endif; ?>
                                    <?php } ?>

                                    <?php //Custom Tab ?>
                                    <?php 
                                        if($themeConfig->get("enable_product_customtab", 0)){
                                            $customtab_html = "";
                                            if( $static_block_id = $themeConfig->get("enable_product_staticblock", "")) { //If isset static block, get static block content to use for custom tab content

                                                $customtab_html .= $this->getLayout()->createBlock('cms/block')->setBlockId($static_block_id)->toHtml();

                                            } elseif($attribute_code = $themeConfig->get("product_customtab_attribute", "")) { //If isset product attribute code, get product attribute content use for custom tab content 
                                                $customtab_html .= Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId() , $attribute_code, Mage::app()->getStore()->getStoreId());;

                                            } else { //Get custom content

                                                $customtab_html .= $themeConfig->get("product_customtab_content","",true);

                                            }

                                            if(!empty($customtab_html)) { //If custom tab content not empty, show the custom tab

                                                $product_customtab = "<div id=\"tab-custom\" class=\"accordion-body panel-collapse collapse box-custom\"><div class=\"accordion-inner panel-body clearfix\">";
                                                $product_customtab .= $customtab_html;
                                                $product_customtab .= '</div></div>';
                                                echo '<div class="panel panel-default accordion-group clearfix">
                                                            <h4 class="accordion-heading panel-heading">
                                                                <a href="#tab-custom" data-parent="#product-tabs-accordion" data-toggle="collapse" class="accordion-toggle">'.$themeConfig->get("product_customtab_name","").'</a>
                                                            </h4>'
                                                            .$product_customtab
                                                      .'</div>';
                                            }
                                            
                                        } ?>

                                    <?php //Reviews Tab ?>  
                                    <?php if($themeConfig->get("enable_product_reviewstab", 1) && $route != "review" && $route !="tempcp") { ?>
                                        <div class="panel panel-default accordion-group clearfix">
                                            <h4 class="accordion-heading panel-heading">
                                                <a href="#tab-reviews" data-parent="#product-tabs-accordion" data-toggle="collapse" class="accordion-toggle"><?php echo Mage::helper('ves_tempcp')->__("Reviews");?></a>
                                            </h4>
                                            <div id="tab-reviews" class="accordion-body panel-collapse collapse block-reviews">
                                                <div class="accordion-inner panel-body clearfix">
                                                <?php echo $this->getChildHtml("review_tab"); ?>
                                                </div>
                                            </div>

                                        </div>
                                    <?php } elseif($route == "review" || $route == "tempcp") { ?>
                                        <div class="panel panel-default  accordion-group clearfix">
                                            <h4 class="accordion-heading panel-heading">
                                                <a href="#tab-reviews" data-parent="#product-tabs-accordion" data-toggle="collapse" class="accordion-toggle"><?php echo Mage::helper('ves_tempcp')->__("Reviews");?></a>
                                            </h4>

                                            <?php echo $this->getChildHtml('product_additional_data');?>

                                        </div>
                                        
                                    <?php }?>
                                </div>
                            </div>
                            <script type="text/javascript">
                                    jQuery(document).ready(function() {
                                        jQuery("#product-tabs-accordion .panel-collapse").first().collapse('toggle')
                                    });
                            </script>
                            <script type="text/javascript">
                                //<![CDATA[
                                    var productAddToCartForm = new VarienForm('product_addtocart_form');
                                    productAddToCartForm.submit = function(button, url) {
                                        if (this.validator.validate()) {
                                            var form = this.form;
                                            var oldUrl = form.action;

                                            if (url) {
                                               form.action = url;
                                            }
                                            var e = null;
                                            try {
                                                this.form.submit();
                                            } catch (e) {
                                            }
                                            this.form.action = oldUrl;
                                            if (e) {
                                                throw e;
                                            }

                                            if (button && button != 'undefined') {
                                                button.disabled = true;
                                            }
                                        }
                                    }.bind(productAddToCartForm);

                                    productAddToCartForm.submitLight = function(button, url){
                                        if(this.validator) {
                                            var nv = Validation.methods;
                                            delete Validation.methods['required-entry'];
                                            delete Validation.methods['validate-one-required'];
                                            delete Validation.methods['validate-one-required-by-name'];
                                            // Remove custom datetime validators
                                            for (var methodName in Validation.methods) {
                                                if (methodName.match(/^validate-datetime-.*/i)) {
                                                    delete Validation.methods[methodName];
                                                }
                                            }

                                            if (this.validator.validate()) {
                                                if (url) {
                                                    this.form.action = url;
                                                }
                                                this.form.submit();
                                            }
                                            Object.extend(Validation.methods, nv);
                                        }
                                    }.bind(productAddToCartForm);
                                //]]>
                            </script>
                        </div>
                
                 </div>
        </div>
</div>
<?php echo $this->getChildHtml('upsell_products') ?>
<?php echo $this->getChildHtml('related_products') ?>
<script type="text/javascript">
jQuery('#tabs a').tabs();
</script> 